DISCORD_TOKEN: 1234
whitelist-igns: false
whitelist-category-name: "Survival"
whitelist-signup-channel-name: "whitelist-igns"
whitelist-chat-channel-name: "whitelist-chat"
whitelist-role-name: "Minecraft verifiziert"
whitelist-role-hex-color: "#0fd9b7"
discord-server-name: "Your Server Name Here"