name: Whitelist
version: '${project.version}'
main: de.itsjxsper.whitelist.Whitelist
api-version: '1.20'
load: STARTUP
authors: [ItsJxsper]
description: Whitelist is a simple whitelist plugin for Bukkit.
commands:
  whitelist:
    description: Handle playtesting operations.
permissions:
  whitelist.admin:
    description: Use playtesting commands.
  whitelist.bypass:
    description: Use bypass All commands.